# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
