# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('moviecollection', '0002_movie_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviecollection.Series'),
        ),
        migrations.AddField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviecollection.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subgenre',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='genre', chained_model_field='genre', default=1, on_delete=django.db.models.deletion.CASCADE, to='moviecollection.Subgenre'),
            preserve_default=False,
        ),
    ]
