# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecollection', '0006_auto_20180318_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='moviecollection.Company'),
        ),
    ]
