# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviecollection', '0007_auto_20180318_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
