# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comiccollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicbook',
            name='publisher',
        ),
        migrations.AddField(
            model_name='comicbook',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comiccollection.Publisher'),
            preserve_default=False,
        ),
    ]
