# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comiccollection', '0002_auto_20170804_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='series_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
