# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year_published', models.IntegerField(max_length=4)),
                ('series', models.IntegerField(blank=True, max_length=3, null=True)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Fiction', 'Fiction'), ('Manga', 'Manga'), ('Sci-Fi', 'Sci-Fi'), ('Classic', 'Classic'), ('Horror', 'Horror'), ('Non-Fiction', 'Non-Fiction')], default='Fiction', max_length=15)),
                ('age_group', models.CharField(choices=[('Children', 'Children'), ('Middle Grade', 'Middle Grade'), ('Young Adult', 'Young Adult'), ('Adult', 'Adult')], default='Children', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
