# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0004_auto_20170710_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookcollection.Series'),
        ),
    ]
