# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0005_auto_20170713_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcollection.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='subgenre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookcollection.Subgenre'),
        ),
    ]
