# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0006_auto_20170718_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookcollection.Genre'),
        ),
    ]
