# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0007_auto_20170718_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audiobook',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
