# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0010_remove_subgenre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookcollection.Genre'),
            preserve_default=False,
        ),
    ]
