# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0011_subgenre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
