# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0012_auto_20170720_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='synopsis',
        ),
    ]
