# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0013_remove_book_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Duck', max_length=50),
            preserve_default=False,
        ),
    ]
