# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0018_auto_20170825_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
