# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0022_auto_20170906_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.CharField(choices=[('children', 'Children'), ('middle_grade', 'Middle Grade'), ('young_adult', 'Young Adult'), ('adult', 'Adult')], default='Children', max_length=15),
        ),
    ]
