# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0023_auto_20170918_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='storage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
