# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0025_series_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='storage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='storage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgenre',
            name='storage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
