# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamecollection.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='subgenre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamecollection.Subgenre'),
            preserve_default=False,
        ),
    ]
