# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0002_auto_20170809_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='subgenre',
        ),
        migrations.DeleteModel(
            name='Subgenre',
        ),
    ]
