# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0004_game_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
