# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0005_auto_20170811_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studio',
            new_name='Developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='studio',
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(to='gamecollection.Developer'),
        ),
    ]
