# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0006_auto_20170811_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='series_number',
        ),
    ]
