# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0007_remove_game_series_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='needs_booklet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='needs_case',
            field=models.BooleanField(default=False),
        ),
    ]
