# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0008_auto_20170817_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_rating',
            field=models.CharField(choices=[('EC', 'Early Childhood'), ('E', 'Everyone'), ('K-A', 'Kids to Adults'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature')], default='E', max_length=15),
        ),
    ]
