# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0009_game_age_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Franchise',
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='series',
            new_name='franchises',
        ),
    ]
