# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0010_auto_20170818_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='franchises',
        ),
        migrations.AddField(
            model_name='game',
            name='franchises',
            field=models.ManyToManyField(blank=True, null=True, to='gamecollection.Franchise'),
        ),
    ]
