# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0011_auto_20170818_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='game',
            name='age_rating',
            field=models.CharField(choices=[('EC', 'Early Childhood'), ('K-A', 'Kids to Adults'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature')], default='E', max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='franchises',
            field=models.ManyToManyField(blank=True, to='gamecollection.Franchise'),
        ),
    ]
