# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0012_auto_20170825_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_rating',
            field=models.CharField(choices=[('EC', 'Early Childhood'), ('K-A', 'Kids to Adults'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature'), ('GA', 'General Audiences')], default='E', max_length=15),
        ),
    ]
