# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecollection', '0013_auto_20170830_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developers',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
